name: Dart CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: cedx/setup-dart@v2
      with:
            architecture: x64
            release-channel: dev
            version: 2.9.0-3.0.dev
    - uses: actions/checkout@v2
    - run: pub get
    - run: pub run test
